---

- hosts: all
  become: true
  tasks:

  - name: update repository index on amz
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: update repository index on Ubuntu
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#Web server
- hosts: web_server
  become: true
  tasks:

  - name: install on ubuntu
    tags: apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install on Amazon
    tags: httpd,amazon
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon"

#Db server
- hosts: db_server
  become: true
  tasks:
    # in this i have provide to control two different os server
  - name: installation on Db server - Ubuntu
    tags: mariadb_ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: installation on Db server - Centos
    tags: mariadb_centos
    apt:
      name:
        - mariadb
      state: latest
      update_cache: yes
    when: ansible_distribution == "Centos"

