---

- hosts: all
  become: true
  tasks:

#Ubuntu
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  # when: ansible_distribution == "Centos" and ansible_distribution == "8.2"
  # when: ansible_distribution in ["Debian","Ubuntu"] 

  - name: install
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

#CentOS
  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"
  # when: ansible_distribution == "Cento" and ansible_distribution == "8.2"
  # when: ansible_distribution in ["Debian","Ubuntu"] 

  - name: install
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

#Opensuse
  - name: update repository index
    zypper:
      update_cache: yes
    when: ansible_distribution == "openSUSE"
  # when: ansible_distribution == "Centos" and ansible_distribution == "8.2"
  # when: ansible_distribution in ["Debian","Ubuntu"] 

  - name: install
    zypper:
      name: apache2
      state: latest
    when: ansible_distribution == "openSUSE"

  - name: add php support for apache
    zypper:
      name: php8 apache2-mod_php8
      state: latest
    when: ansible_distribution == "openSUSE"
