---

- hosts: all
  become: true
  tasks:

#Ubuntu

  - name: install on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#CentOS

  - name: install on CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

#Amazon

  - name: install on Amazon
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon"

#Opensuse

  - name: install on Opensuse
    zypper:
      name:
        - apache2
        - php8 apache2-mod_php8
      state: latest
      update_cache: yes
    when: ansible_distribution == "openSUSE"

