---

- hosts: all
  become: true
  tasks:

#Ubuntu

  - name: install
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#CentOS

  - name: install
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

#Opensuse

  - name: install
    zypper:
      name:
        - apache2
        - php8 apache2-mod_php8
      state: latest
      update_cache: yes
    when: ansible_distribution == "openSUSE"

