---

- hosts: all
  become: true
  tasks:

  - name: install
    package:
      name:
      #This are vasriable name which we have to give in inventory
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
